# https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.17.1 # used to run e2e tests
  node: circleci/node@1.1.6 # used to publish new NPM version

jobs:
  unit:
    description: Checks the code formatting
    executor:
      name: node/default
      tag: '12'
    environment:
      # we don't need Cypress to check code style
      CYPRESS_INSTALL_BINARY: '0'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: CYPRESS_INSTALL_BINARY=0 npm ci
      - run: npm run format:check

  publish:
    description: Publishes the new version of the plugin to NPM
    executor:
      name: node/default
      tag: '12'
    environment:
      # we don't need Cypress to do the release
      CYPRESS_INSTALL_BINARY: '0'
      # trick semantic-release into thinking this is NOT a pull request
      # (under the hood the module env-ci is used to check if this is a PR)
      CIRCLE_PR_NUMBER: ''
      CIRCLE_PULL_REQUEST: ''
      CI_PULL_REQUEST: ''
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run semantic-release

workflows:
  build:
    jobs:
      - unit

      - cypress/install:
          post-steps:
            - run: npm run check:markdown

      - cypress/run:
          name: frontend coverage
          requires:
            - cypress/install
          # grab the workspace created by cypress/install job
          attach-workspace: true
          # we need to start the web application
          start: npm start
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          post-steps:
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: coverage
            # print code coverage summary to the terminal
            # and make sure there the coverage is above certain limit
            - run: npx nyc report --check-coverage true --lines 80
            # make sure second page (about.html) has its JavaScript counted and covered
            - run: npx nyc report --check-coverage true --lines 100 --include cypress/about.js
            # make sure unit tests are covered
            - run: npx nyc report --check-coverage true --lines 100 --include cypress/unit.js

      - cypress/run:
          name: backend coverage
          requires:
            - cypress/install

          # grab the workspace created by cypress/install job
          attach-workspace: true

          start: npm run start:test:backend
          command: npx cypress run --config-file cypress-backend.json

          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          post-steps:
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: coverage
            # print code coverage summary to the terminal
            # and make sure there the coverage is above certain limit
            - run: npx nyc report --check-coverage true --lines 85
            # and look at the server index file - should be fully covered
            - run: npx nyc report --check-coverage true --lines 100 --include test-backend/index.js

      - cypress/run:
          attach-workspace: true
          name: example-before-each-visit
          requires:
            - cypress/install
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          command: npx cypress run --project examples/before-each-visit
          # store screenshots and videos
          store_artifacts: true
          post-steps:
            - run: cat examples/before-each-visit/.nyc_output/out.json
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: examples/before-each-visit/coverage
            # make sure the examples captures 100% of code
            - run:
                command: npx nyc report --check-coverage true --lines 100
                working_directory: examples/before-each-visit
            - run:
                name: Check code coverage 📈
                command: |
                  node ../../scripts/check-coverage main.js
                  node ../../scripts/only-covered main.js
                working_directory: examples/before-each-visit

      - cypress/run:
          attach-workspace: true
          name: example-before-all-visit
          requires:
            - cypress/install
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          command: npx cypress run --project examples/before-all-visit
          # store screenshots and videos
          store_artifacts: true
          post-steps:
            - run: cat examples/before-all-visit/.nyc_output/out.json
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: examples/before-all-visit/coverage
            # make sure the examples captures 100% of code
            - run:
                command: npx nyc report --check-coverage true --lines 100
                working_directory: examples/before-all-visit
            - run:
                name: Check code coverage 📈
                command: |
                  node ../../scripts/check-coverage main.js
                  node ../../scripts/only-covered main.js
                working_directory: examples/before-all-visit

      - cypress/run:
          attach-workspace: true
          name: example-ts-example
          requires:
            - cypress/install
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          working_directory: examples/ts-example
          start: npm start
          wait-on: 'http://localhost:1234'
          command: '../../node_modules/.bin/cypress run'
          post-steps:
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: examples/ts-example/coverage
            - run:
                command: npm run coverage:check
                working_directory: examples/ts-example

            - run:
                name: Check code coverage 📈
                command: |
                  node ../../scripts/check-coverage main.ts
                  node ../../scripts/only-covered main.ts
                working_directory: examples/ts-example

      - cypress/run:
          attach-workspace: true
          name: example-same-folder
          requires:
            - cypress/install
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          command: npx cypress run --project examples/same-folder
          # store screenshots and videos
          store_artifacts: true
          post-steps:
            - run: cat examples/same-folder/.nyc_output/out.json
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: examples/same-folder/coverage
            # make sure the examples captures 100% of code
            - run:
                command: npx nyc report --check-coverage true --lines 100
                working_directory: examples/same-folder
            - run:
                command: npx nyc report --check-coverage true --lines 100 --include unit-utils.js
                working_directory: examples/same-folder
            - run:
                name: Check code coverage 📈
                command: |
                  node ../../scripts/check-coverage main.js
                  node ../../scripts/check-coverage unit-utils.js
                  node ../../scripts/only-covered main.js unit-utils.js
                working_directory: examples/same-folder

      - cypress/run:
          attach-workspace: true
          name: example-support-files
          requires:
            - cypress/install
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          start: npm start --prefix examples/support-files
          wait-on: 'http://localhost:1234'
          command: npx cypress run --project examples/support-files
          # store screenshots and videos
          store_artifacts: true
          post-steps:
            - run: cat examples/support-files/.nyc_output/out.json
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: examples/support-files/coverage
            # make sure the examples captures 100% of code
            - run:
                command: npx nyc report --check-coverage true --lines 100
                working_directory: examples/support-files
            - run:
                name: Check code coverage 📈
                command: |
                  node ../../scripts/check-coverage main.js
                  node ../../scripts/only-covered main.js
                working_directory: examples/support-files

      - publish:
          filters:
            branches:
              only:
                - master
                - beta
          requires:
            - unit
            - frontend coverage
            - backend coverage
            - example-before-each-visit
            - example-before-all-visit
            - example-ts-example
            - example-same-folder
            - example-support-files
