# https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.17.1 # used to run e2e tests
  node: circleci/node@1.1.6 # used to publish new NPM version

jobs:
  unit:
    description: Checks the code formatting
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run format:check

  publish:
    description: Publishes the new version of the plugin to NPM
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run semantic-release

workflows:
  build:
    jobs:
      - unit

      - cypress/install:
          post-steps:
            - run: npm run check:markdown

      - cypress/run:
          name: frontend coverage
          requires:
            - cypress/install
          # grab the workspace created by cypress/install job
          attach-workspace: true
          # we need to start the web application
          start: npm start
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          post-steps:
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: coverage
            # print code coverage summary to the terminal
            # and make sure there the coverage is above certain limit
            - run: npx nyc report --check-coverage true --lines 80
            # make sure second page (about.html) has its JavaScript counted and covered
            - run: npx nyc report --check-coverage true --lines 100 --include cypress/about.js
            # make sure unit tests are covered
            - run: npx nyc report --check-coverage true --lines 100 --include cypress/unit.js

      - cypress/run:
          name: backend coverage
          requires:
            - cypress/install

          # grab the workspace created by cypress/install job
          attach-workspace: true

          start: npm run start:test:backend
          command: npx cypress run --config-file cypress-backend.json

          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          post-steps:
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: coverage
            # print code coverage summary to the terminal
            # and make sure there the coverage is above certain limit
            - run: npx nyc report --check-coverage true --lines 85
            # and look at the server index file - should be fully covered
            - run: npx nyc report --check-coverage true --lines 100 --include test-backend/index.js

      - cypress/run:
          attach-workspace: true
          name: example-before-each-visit
          requires:
            - cypress/install
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          command: npx cypress run --project examples/before-each-visit
          # store screenshots and videos
          store_artifacts: true
          post-steps:
            - run: cat examples/before-each-visit/.nyc_output/out.json
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: examples/before-each-visit/coverage
            # make sure the examples captures 100% of code
            - run:
                command: npx nyc report --check-coverage true --lines 100
                working_directory: examples/before-each-visit

      - cypress/run:
          attach-workspace: true
          name: example-before-all-visit
          requires:
            - cypress/install
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          command: npx cypress run --project examples/before-all-visit
          # store screenshots and videos
          store_artifacts: true
          post-steps:
            - run: cat examples/before-all-visit/.nyc_output/out.json
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: examples/before-all-visit/coverage
            # make sure the examples captures 100% of code
            - run:
                command: npx nyc report --check-coverage true --lines 100
                working_directory: examples/before-all-visit

      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - frontend coverage
            - backend coverage
            - example-before-each-visit
            - example-before-all-visit
